//Login
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const LOGOUT_PENDING = "LOGOUT_PENDING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

//Student
export const ADD_STUDENT_DETAIL_PENDING = "ADD_STUDENT_DETAIL_PENDING";
export const GET_STUDENT_DETAIL_RESULT = "GET_STUDENT_DETAIL_RESULT";
export const ADD_STUDENT_DETAIL_RESULT = "ADD_STUDENT_DETAIL_RESULT";
export const ADD_STUDENT_DETAIL_FAIL = "ADD_STUDENT_DETAIL_FAIL";


export const GET_STUDENT_DETAIL_BY_ID_PENDING = "GET_STUDENT_DETAIL_BY_ID_PENDING";
export const GET_STUDENT_DETAIL_BY_ID_SUCCESS = "GET_STUDENT_DETAIL_BY_ID_SUCCESS";
export const GET_STUDENT_DETAIL_BY_ID_FAIL = "GET_STUDENT_DETAIL_BY_ID_FAIL";

//Feculties
export const ADD_FECULTIES_DETAIL_PENDING = "ADD_FECULTIES_DETAIL_PENDING";
export const ADD_FECULTIES_DETAIL_SUCCESS = "ADD_FECULTIES_DETAIL_SUCCESS";
export const ADD_FECULTIES_DETAIL_FAIL = "ADD_FECULTIES_DETAIL_FAIL";

//Event
export const ADD_EVENT_DETAIL_PENDING = "ADD_EVENT_DETAIL_PENDING";
export const ADD_EVENT_DETAIL_SUCCESS = "ADD_EVENT_DETAIL_SUCCESS";
export const ADD_EVENT_DETAIL_FAIL = "ADD_EVENT_DETAIL_FAIL";

//Holiday
export const ADD_HOLIDAY_DETAIL_PENDING = "ADD_HOLIDAY_DETAIL_PENDING";
export const ADD_HOLIDAY_DETAIL_SUCCESS = "ADD_HOLIDAY_DETAIL_SUCCESS";
export const ADD_HOLIDAY_DETAIL_FAIL = "ADD_HOLIDAY_DETAIL_FAIL";

//Sports
export const ADD_SPORTS_DETAIL_PENDING = "ADD_SPORTS_DETAIL_PENDING";
export const ADD_SPORTS_DETAIL_SUCCESS = "ADD_SPORTS_DETAIL_SUCCESS";
export const ADD_SPORTS_DETAIL_FAIL = "ADD_SPORTS_DETAIL_FAIL";

//Exams
export const ADD_EXAMS_DETAIL_PENDING = "ADD_EXAMS_DETAIL_PENDING";
export const ADD_EXAMS_DETAIL_SUCCESS = "ADD_EXAMS_DETAIL_SUCCESS";
export const ADD_EXAMS_DETAIL_FAIL = "ADD_EXAMS_DETAIL_FAIL";

//Admission
export const ADD_ADMISSION_DETAIL_PENDING = "ADD_ADMISSION_DETAIL_PENDING";
export const ADD_ADMISSION_DETAIL_SUCCESS = "ADD_ADMISSION_DETAIL_SUCCESS";
export const ADD_ADMISSION_DETAIL_FAIL = "ADD_ADMISSION_DETAIL_FAIL";
